# Generated by Django 4.2 on 2023-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=10)),
                ("complement", models.CharField(max_length=100, null=True)),
                ("zip_code", models.IntegerField()),
                ("default", models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
