# Generated by Django 4.2 on 2023-05-08 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.IntegerField(
                validators=[django.core.validators.MaxLengthValidator(8)]
            ),
        ),
    ]
