# Generated by Django 4.2 on 2023-05-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0003_alter_address_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="default",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
