# Generated by Django 4.2 on 2023-05-04 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_alter_cart_products_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
    ]
