# Generated by Django 4.2 on 2023-05-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0003_remove_cart_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_value",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
