# Generated by Django 4.2 on 2023-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_user"),
        ("carts", "0004_alter_cart_total_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="carts", through="carts.CartItem", to="products.product"
            ),
        ),
    ]
