# Generated by Django 4.2 on 2023-05-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0005_order_updated_at_alter_order_hour"),
        ("products", "0009_alter_product_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.CharField(max_length=250)),
                (
                    "stars",
                    models.CharField(
                        choices=[
                            ("detestei", "Hated"),
                            ("não gostei", "Did Not Like"),
                            ("indiferente", "Indifferent"),
                            ("gostei", "Liked"),
                            ("amei", "Loved"),
                        ],
                        default="amei",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_ratings",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_rating",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
