# Generated by Django 4.2 on 2023-05-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0002_rating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="stars",
            field=models.CharField(
                choices=[
                    (1, "Hated"),
                    (2, "Did Not Like"),
                    (3, "Indifferent"),
                    (4, "Liked"),
                    (5, "Loved"),
                ],
                default=5,
            ),
        ),
    ]
