# Generated by Django 4.2 on 2023-05-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEDIDO REALIZADO", "Order Placed"),
                            ("EM ANDAMENTO", "In Progress"),
                            ("ENTREGUE", "Delivered"),
                        ],
                        default="PEDIDO REALIZADO",
                    ),
                ),
                ("hour", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
