# Generated by Django 4.2 on 2023-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEDIDO REALIZADO", "Order Placed"),
                            ("EM ANDAMENTO", "In Progress"),
                            ("ENTREGUE", "Delivered"),
                        ],
                        default="PEDIDO REALIZADO",
                    ),
                ),
                ("hour", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
