# Generated by Django 4.2 on 2023-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="hour",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
