# Generated by Django 4.2 on 2023-05-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="hour",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
