# Generated by Django 4.2 on 2023-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="hour",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
