# Generated by Django 4.2 on 2023-05-07 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_seller", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderseller",
            old_name="products",
            new_name="product",
        ),
    ]
