# Generated by Django 4.2 on 2023-05-08 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order_seller", "0002_rename_products_orderseller_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderseller",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
