# Generated by Django 4.2 on 2023-05-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_product_available"),
        ("order_seller", "0004_alter_orderseller_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderseller",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_seller",
                to="products.product",
            ),
        ),
    ]
