# Generated by Django 4.2 on 2023-05-04 22:38

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=1,
                height_field=230,
                upload_to=products.models.upload_image_product,
                width_field=230,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Teclado", "Teclado"),
                    ("Mouse", "Mouse"),
                    ("Notebook", "Notebook"),
                    ("HD", "Hd"),
                    ("Processador", "Processador"),
                    ("PlacaMãe", "Placamãe"),
                    ("Gabinete", "Gabinete"),
                    ("NN", "Nn"),
                ],
                default="NN",
                max_length=20,
            ),
        ),
    ]
