# Generated by Django 4.2 on 2023-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Teclado", "Teclado"),
                    ("Mouse", "Mouse"),
                    ("Notebook", "Notebook"),
                    ("HD", "Hd"),
                    ("Processador", "Processador"),
                    ("PlacaMãe", "Placamãe"),
                    ("Gabinete", "Gabinete"),
                    ("NN", "Nn"),
                ],
                default="NN",
                max_length=20,
            ),
        ),
    ]
