# Generated by Django 4.2 on 2023-05-05 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="avaliable",
            new_name="available",
        ),
    ]
