# Generated by Django 4.2 on 2023-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_avaliable_product_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(),
        ),
    ]
